import * as fs from 'fs';
import * as path from 'path';

/**
 * ProjectGenerator
 * Universal project factory supporting all languages and frameworks
 */
export class ProjectGenerator {
  private projectPath: string;
  private language: string;
  private framework: string;
  private projectType: string;

  private templates: Record<string, Record<string, any>> = {
    javascript: {
      web: {
        name: 'JavaScript Web App',
        files: {
          'package.json': this.generatePackageJson('javascript', 'web'),
          'index.html': this.generateHTMLIndex(),
          'src/index.js': this.generateJSEntry(),
          '.gitignore': 'node_modules\ndist\n.DS_Store',
        },
      },
      'html-css': {
        name: 'HTML/CSS Website',
        dynamic: true, // Marker: files will be generated based on intent
        files: {}, // Populated dynamically in generateProject()
      },
      react: {
        name: 'React App',
        files: {
          'package.json': this.generatePackageJson('javascript', 'react'),
          'public/index.html': this.generateHTMLIndex(),
          'src/App.jsx': this.generateReactComponent(),
          'src/index.jsx': this.generateReactEntry(),
          '.gitignore': 'node_modules\ndist\n.DS_Store',
        },
      },
      nextjs: {
        name: 'Next.js App',
        files: {
          'package.json': this.generatePackageJson('javascript', 'nextjs'),
          'tsconfig.json': this.generateTSConfig(),
          'next-env.d.ts': '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is generated by Sinter AI and should not be edited manually.\n',
          'app/page.tsx': this.generateNextPage(),
          'app/layout.tsx': this.generateNextLayout(),
          'app/globals.css': this.generateNextGlobals(),
          'lib/project-data.ts': this.generateProjectData(),
          '.gitignore': 'node_modules\n.next\n.DS_Store',
        },
      },
      express: {
        name: 'Express.js API',
        files: {
          'package.json': this.generatePackageJson('javascript', 'express'),
          'index.js': this.generateExpressServer(),
          '.gitignore': 'node_modules\n.DS_Store',
        },
      },
    },
    python: {
      fastapi: {
        name: 'FastAPI App',
        files: {
          'requirements.txt': 'fastapi\nuvicorn\npydantic',
          'main.py': this.generateFastAPIMain(),
          '.gitignore': '__pycache__\nvenv\n.DS_Store',
        },
      },
      django: {
        name: 'Django App',
        files: {
          'requirements.txt': 'django\ndjango-cors-headers',
          'manage.py': this.generateDjangoManage(),
          '.gitignore': '__pycache__\nvenv\ndb.sqlite3\n.DS_Store',
        },
      },
      flask: {
        name: 'Flask App',
        files: {
          'requirements.txt': 'flask\nflask-cors',
          'app.py': this.generateFlaskApp(),
          '.gitignore': '__pycache__\nvenv\n.DS_Store',
        },
      },
    },
    go: {
      gin: {
        name: 'Gin Web Server',
        files: {
          'go.mod': 'module app\n\ngo 1.21\n\nrequire github.com/gin-gonic/gin v1.9.0',
          'main.go': this.generateGinServer(),
          '.gitignore': '\nbinary\nvend\n.DS_Store',
        },
      },
      echo: {
        name: 'Echo Web Server',
        files: {
          'go.mod': 'module app\n\ngo 1.21\n\nrequire github.com/labstack/echo/v4 v4.10.0',
          'main.go': this.generateEchoServer(),
          '.gitignore': '\nbinary\nvend\n.DS_Store',
        },
      },
    },
    rust: {
      actix: {
        name: 'Actix Web Server',
        files: {
          'Cargo.toml': this.generateCargoToml('actix-web'),
          'src/main.rs': this.generateActixMain(),
          '.gitignore': 'target\nCargo.lock\n.DS_Store',
        },
      },
    },
  };

  constructor(projectPath: string) {
    this.projectPath = projectPath;
    this.language = 'javascript';
    this.framework = 'react';
    this.projectType = 'web';
  }

  /**
   * Detect language from intent
   */
  detectLanguage(intent: string): string {
    const lowerIntent = normalizeIntent(intent);

    // ── Explicit HTML/CSS/JS mentions have highest priority ──
    if (
      lowerIntent.includes('html') ||
      lowerIntent.includes('css') ||
      (lowerIntent.includes('javascript') && !lowerIntent.includes('typescript'))
    ) {
      return 'javascript';
    }

    if (
      lowerIntent.includes('python') ||
      lowerIntent.includes('django') ||
      lowerIntent.includes('flask') ||
      lowerIntent.includes('fastapi')
    ) {
      return 'python';
    }
    // Use word boundary matching for 'go' to avoid matching 'good', 'google', 'going', etc.
    if (
      lowerIntent.includes('golang') ||
      lowerIntent.includes('gin ') ||
      lowerIntent.includes('echo ') ||
      /\bgo\b/.test(lowerIntent) && !lowerIntent.includes('good') && !lowerIntent.includes('going') && !lowerIntent.includes('to go')
    ) {
      return 'go';
    }
    if (
      lowerIntent.includes('rust') ||
      lowerIntent.includes('actix')
    ) {
      return 'rust';
    }
    if (
      lowerIntent.includes('typescript') ||
      lowerIntent.includes('next') ||
      lowerIntent.includes('react') ||
      lowerIntent.includes('web') ||
      lowerIntent.includes('website') ||
      lowerIntent.includes('site') ||
      lowerIntent.includes('ويب') ||
      lowerIntent.includes('موقع') ||
      lowerIntent.includes('vue')
    ) {
      return 'javascript';
    }

    return 'javascript'; // Default
  }

  /**
   * Detect framework from intent
   */
  detectFramework(intent: string, language: string): string {
    const lowerIntent = normalizeIntent(intent);

    // ── Explicit HTML/CSS/JS → always html-css template ──
    if (language === 'javascript' && (
      lowerIntent.includes('html') && lowerIntent.includes('css') ||
      lowerIntent.includes('html') && lowerIntent.includes('js') ||
      lowerIntent.includes('to do') || lowerIntent.includes('todo') ||
      lowerIntent.includes('قائمة') || lowerIntent.includes('مهام')
    )) {
      return 'html-css';
    }

    if (language === 'javascript' && (lowerIntent.includes('next') || lowerIntent.includes('nextjs'))) {
      return 'nextjs';
    }
    if (language === 'javascript' && (lowerIntent.includes('express') || lowerIntent.includes('api') || lowerIntent.includes('server') || lowerIntent.includes('backend'))) {
      return 'express';
    }

    const frameworks: Record<string, string[]> = {
      javascript: ['react', 'nextjs', 'express', 'html-css', 'vue', 'svelte'],
      python: ['fastapi', 'django', 'flask'],
      go: ['gin', 'echo', 'fiber'],
      rust: ['actix', 'axum'],
    };

    for (const fw of frameworks[language] || []) {
      if (lowerIntent.includes(fw)) {
        return fw;
      }
    }

    // Simple website requests → html-css, otherwise default
    if (language === 'javascript' && (lowerIntent.includes('website') || lowerIntent.includes('site') || lowerIntent.includes('landing') || lowerIntent.includes('موقع') || lowerIntent.includes('صفحة'))) {
      return 'html-css';
    }
    return Object.keys(this.templates[language])[0] || 'default';
  }

  /**
   * Generate complete project structure
   */
  async generateProject(
    projectName: string,
    intent: string
  ): Promise<{
    success: boolean;
    projectPath: string;
    filesCreated: string[];
    message: string;
  }> {
    try {
      // Detect language and framework
      this.language = this.detectLanguage(intent);
      this.framework = this.detectFramework(intent, this.language);

      const template =
        this.templates[this.language]?.[this.framework];

      if (!template) {
        return {
          success: false,
          projectPath: this.projectPath,
          filesCreated: [],
          message: `No template found for ${this.language}/${this.framework}`,
        };
      }

      // ── Dynamic template: populate files based on intent ──
      if (template.dynamic && this.framework === 'html-css') {
        const lowerIntent = normalizeIntent(intent);
        const isTodo = lowerIntent.includes('todo') || lowerIntent.includes('to do') ||
                       lowerIntent.includes('task') || lowerIntent.includes('مهام') || lowerIntent.includes('قائمة');

        if (isTodo) {
          template.name = 'To-Do List App';
          template.files = {
            'index.html': this.generateTodoHTML(),
            'css/style.css': this.generateTodoCSS(),
            'js/app.js': this.generateTodoJS(),
            'README.md': '# To-Do List App\nOpen index.html in your browser.\nFeatures: Add, complete, delete, filter, localStorage persistence.',
            '.gitignore': '.DS_Store\n*.log',
          };
        } else {
          template.files = {
            'index.html': this.generateStandaloneHTML(),
            'css/style.css': this.generateStandaloneCSS(),
            'js/main.js': this.generateStandaloneJS(),
            'README.md': '# Website\nOpen index.html in your browser.',
            '.gitignore': '.DS_Store\n*.log',
          };
        }
      }

      // Create project directory
      const fullPath = path.join(this.projectPath, projectName);
      if (!fs.existsSync(fullPath)) {
        fs.mkdirSync(fullPath, { recursive: true });
      }

      // Create all files
      const filesCreated: string[] = [];
      for (const [filePath, content] of Object.entries(
        template.files
      )) {
        const fullFilePath = path.join(fullPath, filePath);
        const dir = path.dirname(fullFilePath);

        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }

        fs.writeFileSync(fullFilePath, content as string);
        filesCreated.push(filePath);
      }

      return {
        success: true,
        projectPath: fullPath,
        filesCreated,
        message: `Created ${template.name} project "${projectName}"`,
      };
    } catch (error) {
      return {
        success: false,
        projectPath: this.projectPath,
        filesCreated: [],
        message: `Failed to generate project: ${error}`,
      };
    }
  }

  // Template generators
  private generatePackageJson(language: string, framework: string): string {
    const name = `${language}-${framework}-app`.replace(/\./g, '-');
    const scripts: Record<string, Record<string, string>> = {
      web: {
        dev: 'npx serve .',
        build: 'echo "Static site ready"',
      },
      react: {
        dev: 'vite --host 0.0.0.0',
        build: 'vite build',
        preview: 'vite preview --host 0.0.0.0',
      },
      nextjs: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
      },
      express: {
        dev: 'node index.js',
        start: 'node index.js',
      },
    };
    const dependencies: Record<string, Record<string, string>> = {
      web: {},
      react: {
        '@vitejs/plugin-react': '^5.0.0',
        vite: '^7.0.0',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
      },
      nextjs: {
        next: '^15.0.0',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
      },
      express: {
        express: '^4.18.0',
      },
    };
    const devDependencies: Record<string, Record<string, string>> = {
      web: {},
      react: {},
      nextjs: {
        typescript: '^5.4.0',
        '@types/node': '^20.0.0',
        '@types/react': '^19.0.0',
        '@types/react-dom': '^19.0.0',
      },
      express: {},
    };

    return JSON.stringify(
      {
        name,
        version: '1.0.0',
        description: `${framework} application`,
        private: true,
        scripts: scripts[framework] || scripts.web,
        dependencies: dependencies[framework] || {},
        devDependencies: devDependencies[framework] || {},
      },
      null,
      2
    );
  }

  private generateHTMLIndex(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>App</title>
</head>
<body>
  <div id="root"></div>
  <script src="./src/index.js"><\/script>
</body>
</html>`;
  }

  private generateJSEntry(): string {
    return `console.log('App started!');`;
  }

  private generateReactComponent(): string {
    return `export default function App() {
  return (
    <div>
      <h1>Welcome to React</h1>
      <p>Your app is running!</p>
    </div>
  );
}`;
  }

  private generateReactEntry(): string {
    return `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);`;
  }

  private generateNextPage(): string {
    return `export default function Home() {
  const features = [
    "Workspace-aware generation",
    "Real execution stream",
    "Memory-ready architecture",
    "Validation-first workflow",
  ];

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-16 text-slate-100">
      <section className="mx-auto grid max-w-5xl gap-10 md:grid-cols-[1.2fr_0.8fr] md:items-center">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">
            Generated by Sinter AI
          </p>
          <h1 className="mt-4 text-4xl font-bold tracking-tight md:text-6xl">
            Production-ready starter
          </h1>
          <p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">
            A clean Next.js foundation with typed structure, responsive styling,
            and a layout ready for real product work.
          </p>
        </div>
        <div className="rounded-lg border border-white/10 bg-white/5 p-5 shadow-2xl">
          <div className="mb-4 h-2 rounded-full bg-cyan-400" />
          <div className="space-y-3">
            {features.map((feature) => (
              <div key={feature} className="rounded-md border border-white/10 bg-slate-900/80 px-4 py-3">
                {feature}
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}`;
  }

  private generateNextLayout(): string {
    return `export const metadata = {
  title: 'App',
  description: 'Generated app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`;
  }

  private generateTSConfig(): string {
    return JSON.stringify(
      {
        compilerOptions: {
          target: 'es5',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: { '@/*': ['./*'] },
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2
    );
  }

  private generateNextGlobals(): string {
    return `* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  min-height: 100%;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}`;
  }

  private generateProjectData(): string {
    return `export const generatedAt = new Date().toISOString();

export const projectCapabilities = [
  "project-generation",
  "workspace-awareness",
  "validation",
  "agent-ready",
];`;
  }

  private generateFastAPIMain(): string {
    return `from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {"message": "Hello from FastAPI"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)`;
  }

  private generateDjangoManage(): string {
    return `#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)`;
  }

  private generateFlaskApp(): string {
    return `from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello():
    return {'message': 'Hello from Flask'}

if __name__ == '__main__':
    app.run(debug=True)`;
  }

  private generateGinServer(): string {
    return `package main

import "github.com/gin-gonic/gin"

func main() {
  r := gin.Default()

  r.GET("/", func(c *gin.Context) {
    c.JSON(200, gin.H{
      "message": "Hello from Gin",
    })
  })

  r.Run(":8080")
}`;
  }

  private generateEchoServer(): string {
    return `package main

import (
  "github.com/labstack/echo/v4"
  "net/http"
)

func main() {
  e := echo.New()

  e.GET("/", func(c echo.Context) error {
    return c.JSON(http.StatusOK, map[string]string{
      "message": "Hello from Echo",
    })
  })

  e.Logger.Fatal(e.Start(":8080"))
}`;
  }

  private generateActixMain(): string {
    return `use actix_web::{web, App, HttpServer, HttpResponse};

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .route("/", web::get().to(hello))
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}

async fn hello() -> HttpResponse {
    HttpResponse::Ok().json(serde_json::json!({"message": "Hello from Actix"}))
}`;
  }

  private generateCargoToml(framework: string): string {
    return `[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
${framework} = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = \"1.0\"`;
  }

  private generateStandaloneHTML(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Website</title>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <header class="hero">
    <nav><a href="#">Home</a><a href="#about">About</a><a href="#contact">Contact</a></nav>
    <h1>Welcome to My Website</h1>
    <p>Built with Sinter AI — edit and customize as you like.</p>
    <a href="#about" class="btn">Learn More</a>
  </header>
  <section id="about" class="section">
    <h2>About</h2>
    <p>This is a clean, modern website template ready for customization.</p>
  </section>
  <section id="contact" class="section alt">
    <h2>Contact</h2>
    <p>Reach out via email or social media.</p>
  </section>
  <footer><p>&copy; 2026 My Website. Generated by Sinter AI.</p></footer>
  <script src="js/main.js"><\\/script>
</body>
</html>`;
  }

  private generateStandaloneCSS(): string {
    return `*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',system-ui,sans-serif;background:#0a0e1a;color:#e0e0e0;line-height:1.7}
a{color:#8a4dff;text-decoration:none}
.hero{min-height:80vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;background:linear-gradient(135deg,#0d1224,#1a1048);padding:40px 20px}
.hero nav{position:absolute;top:20px;display:flex;gap:24px;font-size:14px}
.hero nav a{color:#bbb;transition:color .3s}.hero nav a:hover{color:#fff}
.hero h1{font-size:clamp(2rem,5vw,3.5rem);margin-bottom:16px;background:linear-gradient(90deg,#8a4dff,#28e0d1);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.hero p{font-size:1.1rem;color:#aaa;max-width:500px;margin-bottom:24px}
.btn{display:inline-block;padding:12px 32px;background:linear-gradient(90deg,#8a4dff,#6928d1);color:#fff;border-radius:8px;font-weight:600;transition:transform .2s,box-shadow .2s}
.btn:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(138,77,255,.35)}
.section{padding:80px 20px;max-width:800px;margin:0 auto;text-align:center}
.section h2{font-size:2rem;margin-bottom:16px;color:#fff}
.alt{background:#0d1224}
footer{text-align:center;padding:32px;color:#666;font-size:13px;border-top:1px solid #1a1e3a}`;
  }

  private generateStandaloneJS(): string {
    return `document.addEventListener('DOMContentLoaded', function() {
  console.log('Website loaded!');
  // Smooth scroll for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(function(a) {
    a.addEventListener('click', function(e) {
      e.preventDefault();
      var target = document.querySelector(this.getAttribute('href'));
      if (target) target.scrollIntoView({ behavior: 'smooth' });
    });
  });
});`;
  }

  private generateExpressServer(): string {
    return `const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: 'Hello from Express', status: 'running' });
});

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', uptime: process.uptime() });
});

app.listen(PORT, () => {
  console.log('Server running on http://localhost:' + PORT);
});`;
  }

  // ═══════════════════════════════════════════════════════════
  // To-Do List App Templates (Full-featured, beautiful design)
  // ═══════════════════════════════════════════════════════════

  private generateTodoHTML(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>To-Do List App</title>
  <link rel="stylesheet" href="css/style.css">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
  <div class="app">
    <header class="app-header">
      <h1>📋 My Tasks</h1>
      <p class="subtitle">Stay organized, get things done</p>
    </header>

    <div class="input-container">
      <input type="text" id="taskInput" placeholder="What needs to be done?" autocomplete="off">
      <button id="addBtn" title="Add task">+</button>
    </div>

    <div class="filters">
      <button class="filter-btn active" data-filter="all">All</button>
      <button class="filter-btn" data-filter="active">Active</button>
      <button class="filter-btn" data-filter="completed">Completed</button>
    </div>

    <div class="stats">
      <span id="taskCount">0 tasks</span>
      <button id="clearCompleted" class="clear-btn">Clear completed</button>
    </div>

    <ul id="taskList" class="task-list"></ul>

    <div id="emptyState" class="empty-state">
      <div class="empty-icon">✨</div>
      <p>No tasks yet. Add one above!</p>
    </div>
  </div>

  <footer class="app-footer">
    <p>Built with ❤️ by Sinter AI</p>
  </footer>

  <script src="js/app.js"><\\/script>
</body>
</html>`;
  }

  private generateTodoCSS(): string {
    return `/* ═══ To-Do List App — Modern Dark Theme ═══ */
:root {
  --bg: #0a0e1a;
  --surface: rgba(255,255,255,0.04);
  --surface-hover: rgba(255,255,255,0.08);
  --border: rgba(255,255,255,0.08);
  --text: #e8e8f0;
  --text-muted: #8888aa;
  --accent: #8a5cf5;
  --accent-glow: rgba(138,92,245,0.3);
  --success: #34d399;
  --danger: #f87171;
  --radius: 12px;
  --font: 'Inter', system-ui, -apple-system, sans-serif;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: var(--font);
  background: var(--bg);
  color: var(--text);
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 40px 16px;
  background-image:
    radial-gradient(ellipse 600px 400px at 50% 0%, rgba(138,92,245,0.08), transparent),
    radial-gradient(ellipse 400px 300px at 80% 100%, rgba(52,211,153,0.05), transparent);
}

/* ─── App Container ─── */
.app {
  width: 100%;
  max-width: 520px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 20px;
  padding: 32px;
  backdrop-filter: blur(20px);
  box-shadow: 0 8px 32px rgba(0,0,0,0.4);
}

/* ─── Header ─── */
.app-header {
  text-align: center;
  margin-bottom: 28px;
}
.app-header h1 {
  font-size: 28px;
  font-weight: 700;
  background: linear-gradient(135deg, #8a5cf5, #34d399);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}
.subtitle {
  color: var(--text-muted);
  font-size: 14px;
  margin-top: 6px;
}

/* ─── Input ─── */
.input-container {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
}
#taskInput {
  flex: 1;
  background: rgba(255,255,255,0.06);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 14px 18px;
  font-size: 15px;
  color: var(--text);
  font-family: var(--font);
  outline: none;
  transition: border-color 0.2s, box-shadow 0.2s;
}
#taskInput:focus {
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--accent-glow);
}
#taskInput::placeholder { color: var(--text-muted); }

#addBtn {
  width: 50px;
  height: 50px;
  border-radius: var(--radius);
  border: none;
  background: linear-gradient(135deg, #8a5cf5, #6c3ce0);
  color: white;
  font-size: 24px;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: transform 0.15s, box-shadow 0.2s;
  flex-shrink: 0;
}
#addBtn:hover {
  transform: scale(1.05);
  box-shadow: 0 4px 16px var(--accent-glow);
}
#addBtn:active { transform: scale(0.95); }

/* ─── Filters ─── */
.filters {
  display: flex;
  gap: 8px;
  margin-bottom: 16px;
}
.filter-btn {
  flex: 1;
  padding: 8px 12px;
  border: 1px solid var(--border);
  border-radius: 8px;
  background: transparent;
  color: var(--text-muted);
  font-size: 13px;
  font-family: var(--font);
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}
.filter-btn:hover { background: var(--surface-hover); color: var(--text); }
.filter-btn.active {
  background: var(--accent);
  color: white;
  border-color: var(--accent);
}

/* ─── Stats ─── */
.stats {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
  font-size: 13px;
  color: var(--text-muted);
}
.clear-btn {
  background: none;
  border: none;
  color: var(--danger);
  font-size: 12px;
  font-family: var(--font);
  cursor: pointer;
  padding: 4px 8px;
  border-radius: 6px;
  transition: background 0.2s;
}
.clear-btn:hover { background: rgba(248,113,113,0.1); }

/* ─── Task List ─── */
.task-list {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.task-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 16px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  transition: transform 0.15s, background 0.2s, opacity 0.3s;
  animation: slideIn 0.25s ease-out;
}
.task-item:hover { background: var(--surface-hover); }
.task-item.completed .task-text {
  text-decoration: line-through;
  color: var(--text-muted);
}
.task-item.removing {
  animation: slideOut 0.25s ease-in forwards;
}

/* Checkbox */
.task-check {
  width: 22px;
  height: 22px;
  border-radius: 50%;
  border: 2px solid var(--border);
  background: transparent;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  transition: all 0.2s;
  flex-shrink: 0;
  color: transparent;
}
.task-check:hover { border-color: var(--success); }
.task-item.completed .task-check {
  background: var(--success);
  border-color: var(--success);
  color: white;
}

.task-text {
  flex: 1;
  font-size: 15px;
  color: var(--text);
  word-break: break-word;
}

.task-delete {
  width: 30px;
  height: 30px;
  border-radius: 8px;
  border: none;
  background: transparent;
  color: var(--text-muted);
  font-size: 16px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.15s;
  opacity: 0;
  flex-shrink: 0;
}
.task-item:hover .task-delete { opacity: 1; }
.task-delete:hover { background: rgba(248,113,113,0.15); color: var(--danger); }

/* ─── Empty State ─── */
.empty-state {
  text-align: center;
  padding: 40px 20px;
  color: var(--text-muted);
}
.empty-icon { font-size: 40px; margin-bottom: 12px; }
.empty-state.hidden { display: none; }

/* ─── Footer ─── */
.app-footer {
  margin-top: 32px;
  text-align: center;
  color: var(--text-muted);
  font-size: 12px;
}

/* ─── Animations ─── */
@keyframes slideIn {
  from { opacity: 0; transform: translateY(-8px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes slideOut {
  from { opacity: 1; transform: translateX(0); }
  to { opacity: 0; transform: translateX(40px); }
}

/* ─── Responsive ─── */
@media (max-width: 560px) {
  body { padding: 20px 12px; }
  .app { padding: 20px; border-radius: 16px; }
  .app-header h1 { font-size: 24px; }
}`;
  }

  private generateTodoJS(): string {
    return `(function() {
  'use strict';

  // ─── State ─────────────────────────────────────────
  var STORAGE_KEY = 'sinter-todo-tasks';
  var tasks = loadTasks();
  var currentFilter = 'all';

  // ─── DOM Elements ──────────────────────────────────
  var taskInput = document.getElementById('taskInput');
  var addBtn = document.getElementById('addBtn');
  var taskList = document.getElementById('taskList');
  var taskCount = document.getElementById('taskCount');
  var clearBtn = document.getElementById('clearCompleted');
  var emptyState = document.getElementById('emptyState');
  var filterBtns = document.querySelectorAll('.filter-btn');

  // ─── Event Listeners ──────────────────────────────
  addBtn.addEventListener('click', addTask);
  taskInput.addEventListener('keypress', function(e) {
    if (e.key === 'Enter') addTask();
  });
  clearBtn.addEventListener('click', clearCompleted);
  filterBtns.forEach(function(btn) {
    btn.addEventListener('click', function() {
      currentFilter = this.getAttribute('data-filter');
      filterBtns.forEach(function(b) { b.classList.remove('active'); });
      this.classList.add('active');
      render();
    });
  });

  // ─── Core Functions ───────────────────────────────
  function addTask() {
    var text = taskInput.value.trim();
    if (!text) return;

    tasks.push({
      id: Date.now(),
      text: text,
      completed: false,
      createdAt: new Date().toISOString()
    });

    taskInput.value = '';
    taskInput.focus();
    saveTasks();
    render();
  }

  function toggleTask(id) {
    tasks = tasks.map(function(t) {
      if (t.id === id) t.completed = !t.completed;
      return t;
    });
    saveTasks();
    render();
  }

  function deleteTask(id) {
    var el = document.querySelector('[data-id="' + id + '"]');
    if (el) {
      el.classList.add('removing');
      setTimeout(function() {
        tasks = tasks.filter(function(t) { return t.id !== id; });
        saveTasks();
        render();
      }, 250);
    }
  }

  function clearCompleted() {
    tasks = tasks.filter(function(t) { return !t.completed; });
    saveTasks();
    render();
  }

  // ─── Render ───────────────────────────────────────
  function render() {
    var filtered = tasks.filter(function(t) {
      if (currentFilter === 'active') return !t.completed;
      if (currentFilter === 'completed') return t.completed;
      return true;
    });

    taskList.innerHTML = '';

    filtered.forEach(function(task) {
      var li = document.createElement('li');
      li.className = 'task-item' + (task.completed ? ' completed' : '');
      li.setAttribute('data-id', task.id);

      var check = document.createElement('button');
      check.className = 'task-check';
      check.innerHTML = task.completed ? '✓' : '';
      check.title = task.completed ? 'Mark as active' : 'Mark as complete';
      check.addEventListener('click', function() { toggleTask(task.id); });

      var span = document.createElement('span');
      span.className = 'task-text';
      span.textContent = task.text;

      var del = document.createElement('button');
      del.className = 'task-delete';
      del.innerHTML = '✕';
      del.title = 'Delete task';
      del.addEventListener('click', function() { deleteTask(task.id); });

      li.appendChild(check);
      li.appendChild(span);
      li.appendChild(del);
      taskList.appendChild(li);
    });

    // Update stats
    var active = tasks.filter(function(t) { return !t.completed; }).length;
    var total = tasks.length;
    var done = total - active;
    taskCount.textContent = active + ' task' + (active !== 1 ? 's' : '') + ' remaining' + (done > 0 ? ' · ' + done + ' done' : '');

    // Empty state
    if (filtered.length === 0) {
      emptyState.classList.remove('hidden');
      if (currentFilter === 'completed') {
        emptyState.querySelector('p').textContent = 'No completed tasks yet.';
      } else if (currentFilter === 'active') {
        emptyState.querySelector('p').textContent = 'All tasks done! 🎉';
      } else {
        emptyState.querySelector('p').textContent = 'No tasks yet. Add one above!';
      }
    } else {
      emptyState.classList.add('hidden');
    }

    // Show/hide clear button
    clearBtn.style.display = done > 0 ? 'block' : 'none';
  }

  // ─── Storage ──────────────────────────────────────
  function saveTasks() {
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks)); } catch(e) {}
  }

  function loadTasks() {
    try {
      var data = localStorage.getItem(STORAGE_KEY);
      return data ? JSON.parse(data) : [];
    } catch(e) { return []; }
  }

  // ─── Init ─────────────────────────────────────────
  render();
  taskInput.focus();
})();`;
  }
}

export default ProjectGenerator;

function normalizeIntent(intent: string): string {
  return intent
    .toLowerCase()
    .replace(/next\.js/g, 'nextjs')
    .replace(/next js/g, 'nextjs');
}
